root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main.exe"
  cmd = "$env:MODE='development'; go build -o ./tmp/main.exe ."
  exclude_dir = ["assets", "tmp", "bin", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tmpl", "html", "env"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_signal = "kill"
  stop_wait = 500

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "magenta"

[log]
  time = true

[misc]
  clean_on_exit = true
